sampling:
  - layer: 1
    neighbor: 
      - 10
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 32
memory: 
  - type: 'node'
  #'node'
    dim_time: 100
    deliver_to: 'self'
    mail_combine: 'last'
    memory_update: 'gru'
    mailbox_size: 1
    combine_node_feature: True
    dim_out: 100
    historical: True
gnn:
  - arch: 'transformer_attention'
    use_src_emb: False
    use_dst_emb: False
    layer: 1
    att_head: 2
    dim_time: 100
    dim_out: 100
    historical: True
train:
  - epoch: 20
    batch_size: 3000
    # reorder: 16
    lr: 0.0002
    dropout: 0.2
    att_dropout: 0.2
    all_on_gpu: True