sampling:
  - strategy: 'identity'
    history: 1

memory: 
  - type: 'node'
    dim_time: 100
    deliver_to: 'self'
    mail_combine: 'last'
    memory_update: 'rnn'
    historical_fix: False
    async: True
    mailbox_size: 1
    combine_node_feature: True
    dim_out: 100
gnn:
  - arch: 'identity'
    use_src_emb: False
    use_dst_emb: False
    time_transform: 'JODIE'
train:
  - epoch: 250
    batch_size: 1000
    lr: 0.0002
    dropout: 0.1
    all_on_gpu: True