sampling:
  - layer: 2
    neighbor: 
      - 10
      - 10
    strategy: 'uniform'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 32
gnn:
  - arch: 'transformer_attention'
    use_src_emb: False
    use_dst_emb: False
    layer: 1
    att_head: 2
    dim_time: 100
    dim_out: 100
train:
  - epoch: 100
    batch_size: 3000
    # reorder: 16
    lr: 0.0001
    dropout: 0.2
    att_dropout: 0.2
    all_on_gpu: True